### ISSUE TITLE
Fix the organization display name on the Services page

### ISSUE THREAD

**Issue by raamb** [singnet/snet-dapp#298]
We need to get the display name of the organization from IPFS and display that on the DApp ui

**Comment by Vivek205** [comment]
This is same as the name change of singnet in serviceDetails suggested by Greg. Attaching the screenshots. @raamb please confirm and close![Screenshot from 2019-09-16 17-10-07.png](https://images.zenhubusercontent.com/5cbd5c85b2dda007eb1d37e6/c123da6e-44c6-4433-af06-b8e7c9fcbc1c)![Screenshot from 2019-09-16 17-09-44.png](https://images.zenhubusercontent.com/5cbd5c85b2dda007eb1d37e6/4ea03bb0-9625-46da-b9b5-0b0abdba0a14)
