### ISSUE TITLE
Text input fields on dapp are not editable

### ISSUE THREAD

**Issue by edyirdaw** [singnet/snet-dapp#584]
Text input fields on dapp are not editable. The text fields are one way of supplying input before trying to call some service at step 2 (configure step) while another method is file upload.

**Comment by arturgontijo** [comment]
Which services?

**Comment by edyirdaw** [comment]
Topic analysis, Network Robustness and Bipartite graph analytics. These are the services that i am maintaining. But it might also be the case for other services that have text input fields.

**Comment by arturgontijo** [comment]
Ok, will check and fix them. Thanks!

**Comment by arturgontijo** [comment]
@edyirdaw Could you please set a Ropsten endpoint up for each of these 3 services and send the address here?

**Comment by edyirdaw** [comment]
Ok, seems publishing on ropsten is must? Currently i am updating the services on mainnet. Once i finish that, i need to multi task to get them published on ropsten with other snet works or possibly ask a new hire (possibly coming soon) to do that.

**Comment by arturgontijo** [comment]
> Ok, seems publishing on ropsten is must?

I can publish the 3 services using the same `service_metadata.json` from Mainnet but using a secondary endpoint. It's very straightforward for me, on your side you will need only to spawn a new `snetd` using a Ropsten config.

> Currently i am updating the services on mainnet.

Their back-end or front-end (dApp UI)? I can fix the front-end since I've missed the text field update cycle.

**Comment by edyirdaw** [comment]
Ok, i will try to publish them on ropsten. I will let you know if i face any issue.

> Their back-end or front-end (dApp UI)? I can fix the front-end since I've missed the text field update cycle.

Am trying to update them on their back-end, mainly with the latest snetd and new configs also.

**Comment by arturgontijo** [comment]
@edyirdaw great, thanks!
Last thing, can you confirm that the results using the "FileUpload" way are ok?

**Comment by edyirdaw** [comment]
I just checked for all three services and the FileUpload functionality works for all.

**Comment by arturgontijo** [comment]
@edyirdaw could you please test the 3 services and check if they are working as expected now?

Feel free to improve/change anything that makes sense for them.

I'll be helping all the services developers on the deployment and integration of new services onto our platform. Let me know if you need any help.

**Comment by edyirdaw** [comment]
Ok i will check them and inform you back.

**Comment by edyirdaw** [comment]
Just checked. Everything works as expected.
